{
 "title": "Settlement-monthlySettlement",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "통합 지표",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "spring_batch_step_seconds_max{spring_batch_step_name=\"monthlySettlementStep\", spring_batch_step_status=\"COMPLETED\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", application=\"settlement-service\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "hikaricp_connections_active{application=\"settlement-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_used_bytes{application=\"settlement-service\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Settlement 연결된 히카리풀 개수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"settlement-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Settlement 힙 메모리 상세 그래프",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"settlement-service\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch 작업 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "spring_batch_step_seconds_max{spring_batch_step_name=\"monthlySettlementStep\", spring_batch_step_status=\"COMPLETED\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}